### ISSUE TITLE
Remove streaming parsing?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/JSON.jl#118]
From what I can guess from the tests, these lines: 
https://github.com/JuliaLang/JSON.jl/blob/3067b990f9d58a2088de8cb571bb14954354732c/src/JSON.jl#L211-L280
are a way to consume JSON objects from a stream. Calling `parse` on an `::IO` consumes and returns on JSON.
However, not only does it add a lot of complexity, it does strange things like just silently ignoring bad input, e.g.
```
julia> import JSON

julia> io = IOBuffer("(fwag]pgafdgdf[4,4]")
IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=19, maxsize=Inf, ptr=1, mark=-1)

julia> JSON.parse(io)
2-element Array{Any,1}:
 4
 4
```
My proposal would be to just nuke this functionality, as its undocumented and arguably incorrect in the way it tolerates junk silently.

It looks like it was written by @WestleyArgentum, with edits by @jiahao, so would be interested in your take.

**Comment by WestleyArgentum** [comment]
I think the criticisms are totally fair (especially the part where silently tolerates junk), but this was super useful when sending json messages over sockets.

I'm trying to think of a better pattern for people who need to do this (one that doesn't involve everyone re-implementing their own slow+buggy buffers from which they parse out json)... but nothing jumps to mind. Might have to go look at other streaming apis for inspiration.

In the mean time, I don't think we should nuke this without coming up with an alternative pattern. I know there are at least a couple code bases (that I don't have access to) where this is relied on...

**Comment by StefanKarpinski** [comment]
Parsing JSON from a stream and writing JSON to a stream incrementally do seem useful but I don't understand why that entails skipping and ignoring junk on the stream.

**Comment by WestleyArgentum** [comment]
Perhaps the problems can be addressed with optional parameters. We could error when something unexpected happens by default, and maybe provide a way to turn that off.

The other glaring problem I see is that there's no way to specify a timeout, so it's quite easy to get stuck forever when trying to parse from an incomplete stream. Maybe that's a limitation of the IO interface we're using, not sure.

**Comment by TotalVerb** [comment]
The streaming parser no longer silently tolerates junk. It's also a lot faster than it was before. Good to close?

**Comment by kmsquire** [comment]
Can be closed pending https://github.com/JuliaLang/METADATA.jl/pull/5380.

Thanks for going through these issues, @TotalVerb.

**Comment by jiahao** [comment]
closed now that METADATA is tagged
