### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/JSON.jl#122]
The JSON data in [this gist](https://gist.github.com/jiahao/11b452b42f125e383dcb), returned from a recent GitHub API query, broke the parser:

```jl
julia> JSON.parsefile("events.json")
ERROR: Missing opening string char
Line: 1
Around: ...ntEvent",actor":{"id":1282691...
                    ^

 in error at error.jl:21
 in _error at /Users/jiahao/.julia/v0.4/JSON/src/Parser.jl:70
 in parse_string at /Users/jiahao/.julia/v0.4/JSON/src/Parser.jl:146
 in parse_object at /Users/jiahao/.julia/v0.4/JSON/src/Parser.jl:117
 in parse_object at /Users/jiahao/.julia/v0.4/JSON/src/Parser.jl:107
 in parse_value at /Users/jiahao/.julia/v0.4/JSON/src/Parser.jl:223
 in parse_array at /Users/jiahao/.julia/v0.4/JSON/src/Parser.jl:85
 in parse_value at /Users/jiahao/.julia/v0.4/JSON/src/Parser.jl:223
 [inlined code] from /Users/jiahao/.julia/v0.4/JSON/src/Parser.jl:322
 in __parse#0__ at no file:0
 in parse at no file
 in anonymous at /Users/jiahao/.julia/v0.4/JSON/src/JSON.jl:286
 in open at ./iostream.jl:114
 [inlined code] from /Users/jiahao/.julia/v0.4/JSON/src/JSON.jl:284
 in __parsefile#2__ at no file:0
 in parsefile at no file
```

I suspect it's getting confused by some of the escaped JSON embedded within some of the GitHub issue comments.

**Comment by TotalVerb** [comment]
Are you sure this JSON is not corrupted? There are a lot of control characters in there. I fetched the json file from the link you provided, and it parsed without error.

**Comment by TotalVerb** [comment]
Although this issue wasn't really "fixed" by this #140, the error message seems to have been improved:

before:
```
ERROR: Missing opening string char
Line: 1
Around: ...ntEvent",actor":{"id":1282691...
                    ^
[ backtrace here ]
```

after:
```
ERROR: ASCII control character in string
Line: 0
Around: ...atars.gitubusercontent.com/u/...
                    ^
[ backtrace here ]
```

So I'm inclined to add this to the issues that #140 will close.

**Comment by TotalVerb** [comment]
I think I misunderstood how autoclosing from PRs worked. GitHub didn't close this automatically. @jiahao is this good to close?

**Comment by kmsquire** [comment]
The original file posted isn't parsable by other JSON readers (e.g., https://github.com/ddopson/underscore-cli), and the error message is clearer, so should be good to close.
