### ISSUE TITLE
tag new release?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/JSON.jl#123]
The main difference from the last tagged version is just the `__precompile__` directive.  It doesn't make a huge difference in the JSON load time at the moment (0.38s vs. 0.58s on my machine), but I'd like to turn on precompilation for IJulia soon (once ZMQ is fixed), and it is good practice to make sure all of the imported modules have `__precompile__` first.

**Comment by IainNZ** [comment]
Something seems screwy on PkgEval with DataStructures in the tests, I wonder if something broken with the dynamic loading of DataStructures with some of the 0.4 changes?

**Comment by IainNZ** [comment]
Can't reproduce locally. Giving Travis a shot, on 0.3, 0.4-rc1, and nightly 0.5, just to see.

**Comment by tkelman** [comment]
The conditional inclusion of DataStructures doesn't work at all with precompilation. If JSON.jl gets precompiled when DataStructures is present, but then re-loaded when DataStructures is not present, we get `ERROR: LoadError: ArgumentError: DataStructures not found in path`. Not good. Either DataStructures should be a hard dependency, or precompilation should be off.
