### ISSUE TITLE
enums

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/JSON.jl#135]
~~~julia
julia> @enum Test T1 T2 T3

julia> T1
T1::Test

julia> JSON.json(T1)
"{}"
~~~

Is there some way to make this come out like `"\"T1\""` as if I had done `JSON.json("T1")`?

Do I need to override some IO stuff?

Thanks

Edit: I subsequently asked about this on [julia-users](https://groups.google.com/forum/#!topic/julia-users/SQ7KWj69_Gs), Hope you don't mind.

PS: My data structure is actually more complicated and involves enum properties, so hopefully the solution is general enough that it will work for an enum embedded within a more complex type. For example:

~~~julia
julia> d = Dict("a" => T1)
Dict{ASCIIString,Test} with 1 entry:
  "a" => T1::Test

julia> JSON.json(d)
"{\"a\":{}}"
~~~

**Comment by dpsanders** [comment]
You can define the following function:

```
JSON.json{T <: Enum}(x::T) = JSON.json(string(x))
```
I guess this should go inside the `JSON` package.

**Comment by EricForgy** [comment]
Thanks @dpsanders ,

That helps with serializing an Enum in isolation, but when it is part of a Dict, it still isn't working.

~~~julia
julia> JSON.json{T <: Enum}(x::T) = JSON.json(string(x))
json (generic function with 3 methods)

julia> JSON.json(T1)
"\"T1\""

julia> d = Dict("a" => T1)
Dict{ASCIIString,Test} with 1 entry:
  "a" => T1::Test

julia> JSON.json(d)
"{\"a\":{}}"
~~~

Any other ideas?

**Comment by EricForgy** [comment]
Looking at JSON.json, it basically calls JSON.print, which calls JSON._print.

There are a number of different JSON._print determined by dispatch, so I think we need a JSON._print for Enums. Will give it a try...
