### ISSUE TITLE
Use Symbol as key of Dict?

### ISSUE THREAD

**Issue by jingpengwu** [JuliaLang/JSON.jl#153]
currently, the type of `key` is `UTF8String`.
In julia, using `Symbol` rather than String as key type is more efficient. How about adding an option to use `Symbol` as the type of keys?

**Comment by yuyichao** [comment]
> In julia, using `Symbol` rather than String as key type is more efficient.

With the caveat that `Symbol`s are never freed. Adding options might be fine. Just want to point this out and that this shouldn't be the default.

**Comment by TotalVerb** [comment]
This is already supported: `parse("""{"hello": "world"}""", dicttype=Dict{Symbol,Any})`

**Comment by jingpengwu** [comment]
great! it works pretty well. Thanks 👍
