### ISSUE TITLE
Should parsefile close the file when done?

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/JSON.jl#155]
I notice that after running JSON.parsefile, the file is still locked (on Windows). Should parsefile close the file when it is finished reading?

https://github.com/JuliaLang/JSON.jl/blob/master/src/JSON.jl#L219-L225

~~~julia
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
~~~

**Comment by yuyichao** [comment]
The file is closed. But I think mmap is not.

**Comment by EricForgy** [comment]
Could be.

I am designing a sample JSON file for a web API and after running parsefile, I cannot save any modifications to the JSON file until I close Julia. Hmm.

**Comment by EricForgy** [comment]
I think you're right. If I set `use_mmap=false`, the file is not locked. I'll do that. Should I keep this issue open? It seems like a bug to me.

**Comment by TotalVerb** [comment]
The problem is with mmap's equivalent on windows. I don't think it can be fixed here.

Either `use_mmap=false` or using `open(JSON.parse, file)` are possible workarounds.

**Comment by EricForgy** [comment]
Thanks @TotalVerb . I'll see if an issue exists over there.
