### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/JSON.jl#156]
JSON 0.6.0 tests has deprecation warnings on v0.5 and JSON master doesn't. So could you tag a new release please?

**Comment by EricForgy** [comment]
I just submitted PR #157 . Might be good to fix that and then tag?

**Comment by ranjanan** [comment]
Oh I must have missed that `readall` depwarn. Thanks, and sure! :)

**Comment by ranjanan** [comment]
Now that these #157 is merged, can we tag a new release?

**Comment by TotalVerb** [comment]
@kmsquire How about tagging 0.6.1 at 38f4d37479fe227fd00a56a085ecd3a63456a36c (the commit before #151 was merged), and 0.7.0 at 495c75ff122abcac409cc79b7c4bc7d005872d7a (the commit after #151 is merged)? Just in case 0.7.0 breaks things, upper bounds can be added to packages to a depwarn-free tag.

**Comment by kmsquire** [comment]
That sounds fine to me.  Shall I do it, or will you?

**Comment by TotalVerb** [comment]
I don't think I have the ability to push tags.

**Comment by kmsquire** [comment]
Np. https://github.com/JuliaLang/METADATA.jl/pull/5988

**Comment by tkelman** [comment]
@TotalVerb I think if you have write access here then you should be able to push tags.

**Comment by TotalVerb** [comment]
@tkelman Hmm, maybe I'll have to try again in the future.
