### ISSUE TITLE
Protected import of "DataStructures.OrderedDict" fails on Julia 0.3.5.

### ISSUE THREAD

**Issue by ChrisTimperley** [JuliaLang/JSON.jl#91]
The following error is encountered when attempting to call the parse function with ordering enabled:
```
julia> JSON.parse("{\"x\": 3}"; ordered = true)
ERROR: OrderedDict not defined
 in parse_object at /home/christopher/.julia/v0.3/JSON/src/Parser.jl:109
 in parse_value at /home/christopher/.julia/v0.3/JSON/src/Parser.jl:231
 in parse at /home/christopher/.julia/v0.3/JSON/src/Parser.jl:318
```
The `import` statement on line 7 of Parser.jl throws the following exception:
```
ErrorException("unsupported or misplaced expression import")
```
The fallback `OrderedDict` function, which should give a warning that DataStructures.jl is missing seems to fail to be realised within the scope of the module.

If we (wrongly) assume that DataStructures.OrderedDict is present, we can avoid the error by replacing the "try/catch" block that deals with any failures to import `OrderedDict` from the DataStructures package with the following import statement:

```
import DataStructures.OrderedDict
```

So it would appear as if Julia is encountering some issues when calling `import` from inside a try/catch block.

**Environment**
Julia 0.3.5 (x86_64)
Ubuntu 12.04 LTS (x64)
Both the JSON and DataStructures packages installed.

**Comment by kmsquire** [comment]
@ChrisTimperley, sorry no one got to this sooner.  #92 should fix this.  That will get merged when testing turns green.
