### ISSUE TITLE
Round trip and escaped double quotes

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/JSON.jl#95]
Hi,

In javascript, I stringify an object:

    > obj = {"array": [1,2,3], "customer": "type1"}
    <- Object {array: Array[3], customer: "type1"}
    > s = JSON.stringify(obj)
    <- "{"array":[1,2,3],"customer":"type1"}"    [Note: No escaped double quotes.]

and can parse it:

    > JSON.parse(s)
    <- Object {array: Array[3], customer: "type1"}

 I get back the same object I started with. I think this seems reasonable.

However, if I "post" the stringified object to a Julia server and try to parse it, I obviously get errors because Julia is expecting the double quotes to be escaped.

Is javascript being too loose or is Julia being too tight? Is there some way for me to easily stringify javascript objects so they can be consumed by Julia? Or is there some way to get Julia to consume stringified objects from javascript without escaped double quotes? 

I would presume this is the primary use case for JSON.jl. Is this something in JSON.jl that needs fixing or is this an acceptable state?

I can't make promises, but if this is something worth fixing, I could give it a shot.

**Comment by samuelcolvin** [comment]
This doesn't look to me like a fault with JSON.jl or even Julia, just that your javascript prompt displays strings with quotes in them without escape characters.

In the end if you provide JSON.jl with a string with quotes in it obviously copes fine:

```
julia> using JSON

julia> s = "{\"array\":[1,2,3],\"customer\":\"type1\"}"
"{\"array\":[1,2,3],\"customer\":\"type1\"}"

julia> println(s)
{"array":[1,2,3],"customer":"type1"}  # [Note: No escaped double quotes.]

julia> JSON.parse(s)
Dict{String,Any} with 2 entries:
  "customer" => "type1"
  "array"    => {1,2,3}
```

**Comment by EricForgy** [comment]
Hi Samuel,

Thanks for your quick response. As we say here in Hong Kong, "Aiyaaaaaa". I was doing something even dumber than misinterpreting the output to the screen and thought my problem was relating to escaped double quotes. Sorry about that. My code seems fine now.
