### ISSUE TITLE
Illegal indexing in `_count_before`?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/JSON.jl#99]
https://github.com/JuliaLang/JSON.jl/blob/7f5266221deb2063c83dee28a49d251d71f5cc46/src/Parser.jl#L63-L71

I was getting errors about indexing into a non-valid character from this. How should this be written to avoid indexing into the string like this?

**Comment by stevengj** [comment]
For example, something like this should work:
```
count = 0
for (i,c) in enumerate(haystack)
     i >= __end && return count
     count += c == needle
end
return count
```
You need to use `next` (i.e. string iterators) or `nextind` to iterate through a string.

**Comment by IainNZ** [comment]
`JSON.parse("[\"🍕\"_\"🍕\"")` triggers this
